apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: reservavuelos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: reservavuelos
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: laurasaree/reservavuelos-db:v2
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reservavuelos-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: reserva_vuelos
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: reservavuelos
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
